### ISSUE TITLE
Questions about NPC sounds and general sounds

### ISSUE THREAD

**Issue by dgonyier** [overtools/OWLib#90]
Questions about using Datatool

What is the command syntax to extract voice sounds for a specific NPC (Athena)? I see mention of a `v` option, but I couldn't get that to work with `datatool`

Also, a general sound question: are the sounds extracted as lossly or lossless OGG Vorbis files? If they are lossy, have you considered FLAC instead for lossless sound extraction?

Thanks.

**Comment by yretenai** [comment]
Athena sounds are not often grouped together and as such harder to extract.

I believe all the sound files are lossless, but it's up to how Blizzard encoded the Wwise WEM wavs. Encoding to FLAC is not an option as the only feasible encoding path is from wem to ogg due to the only library/program being ww2ogg.

**Comment by dgonyier** [comment]
> 
> 
> Athena sounds are not often grouped together and as such harder to extract.
> 

I think I managed to get them with the `extract-voice-sets` mode. Lots of disk space though.

> I believe all the sound files are lossless, but it's up to how Blizzard encoded the Wwise WEM wavs. Encoding to FLAC is not an option as the only feasible encoding path is from wem to ogg due to the only library/program being ww2ogg.

Good to know. Thanks.

**Comment by Js41637** [comment]
There is now an `extract-npc-voice` command that includes all Athena voicelines and all the other npcs in the game.
